### ISSUE TITLE
运行时出现未知错误

### ISSUE THREAD

**Issue by Avimitin** [BennyThink/pyweathercn#2]
调用模块方法时出现未知错误，请问是爬虫爬不到数据了吗。

```
Unknown error. Please contact @BennyThink via Telegram.
ERROR:root:Traceback (most recent call last):
  File "F:\Telegram_Bot\python_bot\venv\lib\site-packages\pyweathercn\craw.py", line 127, in make_json
    sample = {"city": city, "aqi": js_hour_aqi(soup), "tip": today_tip(soup), "temp": js_hour_temp(soup),
  File "F:\Telegram_Bot\python_bot\venv\lib\site-packages\pyweathercn\craw.py", line 34, in js_hour_aqi
    od = json.loads(js[js.index('=') + 2:js.index(';')])
ValueError: substring not found
```

**Comment by BennyThink** [comment]
可能。回去查下

Avimitin <notifications@github.com> 于 2020年4月10日周五 14:46写道：

**Comment by BennyThink** [comment]
Please use version 1.0.8.
https://pypi.org/project/pyweathercn/1.0.8/

Probably need to wait until mirror syncs.

```bash
pip3 install pyweathercn==1.0.8
```

**Comment by Avimitin** [comment]
非常感谢
